#数据库连接
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://134.175.118.250:3306/byte_market?characterEncoding=utf-8
    username: root
    password: 123456

#设置文件传输大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB


mybatis-plus:
  mapper-locations: classpath:/mapper/xml/*Mapper.xml
  typeAliasesPackage: com.android.bytemarket.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
